import { Bell, CheckCheck } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { MarketplaceLayout } from "@/components/MarketplaceLayout";
import { Button } from "@/components/ui/button";
import { dateTime } from "@/lib/marketplace";
import { trpc } from "@/lib/trpc";
export default function Notifications() { const auth = useAuth(); const utils = trpc.useUtils(); const list = trpc.marketplace.notifications.list.useQuery(undefined, { enabled: auth.isAuthenticated }); const mark = trpc.marketplace.notifications.markRead.useMutation({ onSuccess: () => utils.marketplace.notifications.list.invalidate() }); if (!auth.isAuthenticated && !auth.loading) return <MarketplaceLayout title="الإشعارات"><div className="rounded-3xl bg-white p-8 text-center"><Button onClick={() => startLogin()} className="rounded-xl bg-[#e98716] font-black">تسجيل الدخول لعرض الإشعارات</Button></div></MarketplaceLayout>; return <MarketplaceLayout title="الإشعارات" actions={<Button variant="outline" onClick={() => mark.mutate({ all: true })} disabled={!list.data?.some((item) => !item.isRead)} className="rounded-xl"><CheckCheck className="ml-2 h-4 w-4" />تحديد الكل مقروءًا</Button>}>{list.isLoading ? <div className="h-32 animate-pulse rounded-3xl bg-slate-200" /> : list.data?.length ? <div className="space-y-3">{list.data.map((item) => <Link key={item.id} href={item.href || "/notifications"} onClick={() => !item.isRead && mark.mutate({ id: item.id, all: false })} className={`block rounded-2xl p-4 shadow-sm ring-1 transition ${item.isRead ? "bg-white ring-slate-200" : "bg-[#fffaf1] ring-[#f7ad32]/40"}`}><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#172b4d] text-[#f7ad32]"><Bell className="h-5 w-5" /></span><div><h2 className="font-black text-[#172b4d]">{item.title}</h2><p className="mt-1 text-sm text-slate-600">{item.body}</p><time className="mt-2 block text-xs text-slate-400">{dateTime.format(new Date(item.createdAt))}</time></div></div></Link>)}</div> : <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">لا توجد إشعارات جديدة.</div>}</MarketplaceLayout>; }
